// <auto-generated />
namespace Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Server61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Server61));
        
        string IMigrationMetadata.Id
        {
            get { return "202007210906254_Server61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
